### ISSUE TITLE
feat: create auto-release.yml for automatic release whenever a tag is pushed...

### ISSUE THREAD

**Issue by DhruvWebDev** [SolanaCore/multisig#41]
Example: 
```yml
name: Create GitHub Release

on:
  push:
    tags:
      - 'v*' # triggers on tags like v1.0.0, v2.3.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
```
